services:
    timeTracker:
        class:      \Simtt\Domain\TimeTracker
        arguments:  ['@logHandler', '%config.precision%']
    logHandler:
        class:      \Simtt\Infrastructure\Service\LogHandler
        arguments:  ['@logFileFinder']
    logFileFinder:
        class:      \Simtt\Infrastructure\Service\LogFileFinder
        arguments:  ['%config.logDir%']
    parser:
        class:      \Simtt\Application\Command\Parser
        arguments:  ['%parserPattern%']

    simtt.cmd:
        class:      \Simtt\Application\Command\Simtt
        arguments:  ['@parser', '%prompter%']
    start.cmd:
        class:      \Simtt\Application\Command\Start
        arguments:  ['%currentLogFile%', '@timeTracker']
    stop.cmd:
        class:      \Simtt\Application\Command\Stop
        arguments:  ['%currentLogFile%', '@timeTracker']
    status.cmd:
        class:      \Simtt\Application\Command\Status
        arguments:  ['@logHandler']
    log.cmd:
        class:      \Simtt\Application\Command\Log
        arguments:  ['@logHandler', '%config.showLogItems%']
    now.cmd:
        class:      \Simtt\Application\Command\Now
        arguments:  ['%config.precision%']

