services:
    timeTracker:
        class:      \Simtt\Domain\TimeTracker
        arguments:  ['@logHandler']
    logHandler:
        class:      \Simtt\Infrastructure\Service\LogHandler
        arguments:  ['@logFileFinder']
    logFileFinder:
        class:      \Simtt\Infrastructure\Service\LogFileFinder
        arguments:  ['%logDir%']
    parser:
        class:      \Simtt\Application\Command\Parser
        arguments:  ['%parserPattern%']

    simtt.cmd:
        class:      \Simtt\Application\Command\Simtt
        arguments:  ['@parser', '%prompter%']
    start.cmd:
        class:      \Simtt\Application\Command\Start
        arguments:  ['%currentLogFile%', '@timeTracker']
    status.cmd:
        class:      \Simtt\Application\Command\Status
        arguments:  ['@logHandler']

