services:
    timeTracker:
        class:      Simtt\Domain\TimeTracker
        arguments:  ['@logHandler', '%config.precision%']
    logHandler:
        class:      Simtt\Infrastructure\Service\LogHandler
        arguments:  ['@logFileFinder']
    logFileFinder:
        class:      Simtt\Infrastructure\Service\LogFileFinder
        arguments:  ['%config.logDir%']
    parser:
        class:      Simtt\Application\Command\Parser
        arguments:  ['%parserPattern%']
    recentTaskList:
        class:      Simtt\Infrastructure\Service\RecentTaskList
        arguments:  ['@logFileFinder']
    recentTasksPrinter:
        class:      Simtt\Infrastructure\Service\RecentTasksPrinter
        arguments:  ['@recentTaskList', '%config.showTaskItems%']
    taskPrompter:
        class:      Simtt\Infrastructure\Service\TaskPrompter

    simtt.cmd:
        class:      Simtt\Application\Command\Simtt
        arguments:  ['@parser', '%prompter%']
    start.cmd:
        class:      Simtt\Application\Command\Start
        arguments:  [
            '@logFileFinder',
            '@timeTracker',
            '@recentTasksPrinter',
            '@taskPrompter',
            '%prompter%',
        ]
    stop.cmd:
        class:      Simtt\Application\Command\Stop
        arguments:  [
            '@logFileFinder',
            '@timeTracker',
            '@recentTasksPrinter',
            '@taskPrompter',
            '%prompter%',
        ]
    status.cmd:
        class:      Simtt\Application\Command\Status
        arguments:  ['@logHandler']
    log.cmd:
        class:      Simtt\Application\Command\Log
        arguments:  ['@logHandler', '%config.showLogItems%']
    tasks.cmd:
        class:      Simtt\Application\Command\Tasks
        arguments:  ['@recentTaskList', '%config.showTaskItems%']
    task.cmd:
        class:      Simtt\Application\Command\Task
        arguments:  ['@logHandler', '%prompter%', '@recentTasksPrinter', '@taskPrompter']
    comment.cmd:
        class:      Simtt\Application\Command\Comment
        arguments:  ['@logHandler', '%prompter%']
    day.cmd:
        class:      Simtt\Application\Command\Day
        arguments:  ['@logHandler']
    week.cmd:
        class:      Simtt\Application\Command\Week
        arguments:  ['@logHandler']
    month.cmd:
        class:      Simtt\Application\Command\Month
        arguments:  ['@logHandler']
    yesterday.cmd:
        class:      Simtt\Application\Command\Yesterday
    now.cmd:
        class:      Simtt\Application\Command\Now
        arguments:  ['%config.precision%']

