#!/usr/bin/env php
<?php
declare(strict_types=1);

/**
 * @author Steffen Zeidler <sigma_z@sigma-scripts.de>
 */
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/src/bootstrap.php';

use Symfony\Component\Console\Application;

define('SIMTT_VERSION', '0.0.1');

echo 'A simple interactive time tracker in PHP by Steffen Zeidler';
echo "\nNOTE: This is an early project state. Therefore the tool can't do much at the moment.\n\n";

$simttInteractive = ($_SERVER['argv'][1] ?? null) === '-i';

$application = new Application('Simtt', SIMTT_VERSION);
if ($simttInteractive) {
    unset($_SERVER['argv'][1]);
    /** @noinspection PhpUnhandledExceptionInspection,PhpParamsInspection */
    $application->add($containerBuilder->get('simtt.cmd'));
    $application->setDefaultCommand('Simtt');
}

/** @noinspection PhpUnhandledExceptionInspection,PhpParamsInspection */
$application->add($containerBuilder->get('start.cmd'));
/** @noinspection PhpUnhandledExceptionInspection,PhpParamsInspection */
$application->add($containerBuilder->get('stop.cmd'));
/** @noinspection PhpUnhandledExceptionInspection,PhpParamsInspection */
$application->add($containerBuilder->get('status.cmd'));
/** @noinspection PhpUnhandledExceptionInspection,PhpParamsInspection */
$application->add($containerBuilder->get('comment.cmd'));
/** @noinspection PhpUnhandledExceptionInspection,PhpParamsInspection */
$application->add($containerBuilder->get('log.cmd'));
/** @noinspection PhpUnhandledExceptionInspection,PhpParamsInspection */
$application->add($containerBuilder->get('day.cmd'));
/** @noinspection PhpUnhandledExceptionInspection,PhpParamsInspection */
$application->add($containerBuilder->get('yesterday.cmd'));
/** @noinspection PhpUnhandledExceptionInspection,PhpParamsInspection */
$application->add($containerBuilder->get('now.cmd'));
$application->run();
