#!/usr/bin/env php
<?php
declare(strict_types=1);

/**
 * @author Steffen Zeidler <sigma_z@sigma-scripts.de>
 */

foreach ([__DIR__ . '/vendor/autoload.php', __DIR__ . '/../../autoload.php'] as $autoloadFile) {
    if (file_exists($autoloadFile)) {
        require_once $autoloadFile;
        break;
    }
}
$containerBuilder = require_once __DIR__ . '/src/bootstrap.php';

use Symfony\Component\Console\Application;

const SIMTT_VERSION = '1.2.1';

echo 'Simtt: the simple interactive time tracker in PHP by Steffen Zeidler' . "\n";

$simttInteractive = ($_SERVER['argv'][1] ?? null) === '-i';

$application = new Application('Simtt', SIMTT_VERSION);
if ($simttInteractive) {
    unset($_SERVER['argv'][1]);
    $application->add($containerBuilder->get('simtt.cmd'));
    $application->setDefaultCommand('Simtt');
}

$application->add($containerBuilder->get('start.cmd'));
$application->add($containerBuilder->get('stop.cmd'));
$application->add($containerBuilder->get('continue.cmd'));
$application->add($containerBuilder->get('status.cmd'));
$application->add($containerBuilder->get('task.cmd'));
$application->add($containerBuilder->get('comment.cmd'));
$application->add($containerBuilder->get('log.cmd'));
$application->add($containerBuilder->get('day.cmd'));
$application->add($containerBuilder->get('week.cmd'));
$application->add($containerBuilder->get('month.cmd'));
$application->add($containerBuilder->get('yesterday.cmd'));
$application->add($containerBuilder->get('now.cmd'));
$application->add($containerBuilder->get('tasks.cmd'));
$application->run();
