#!/usr/bin/env php
<?php

/**
 * @author Steffen Zeidler <sigma_z@sigma-scripts.de>
 */

define('SIMTT_VERSION', '0.0.1');
printf('Simtt %s - a simple interactive time tracker in PHP by Steffen Zeidler', SIMTT_VERSION);
echo "\n";
echo "\nUnfortunately this is an early project state. Therefore the tool can't do much at the moment.\n";
